---
version: '3.8'
services:
#
# >>> cdc
# https://eventuate.io/docs/manual/eventuate-tram/latest/cdc-configuration.html
#
  cdc:
    image: eventuateio/eventuate-cdc-service:0.9.0.RELEASE
    hostname: cdc
    container_name: cdc
    ports:
      - 8099:8080
    depends_on:
      - order-db
      - payment-db
      - kafka
    environment:
      DEBUG: "true"

      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181

      EVENTUATE_CDC_PIPELINE_PIPELINE1_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_PIPELINE1_READER: reader1
      EVENTUATE_CDC_PIPELINE_PIPELINE1_EVENTUATEDATABASESCHEMA: order
      #EVENTUATE_CDC_PIPELINE_PIPELINE1_SOURCETABLENAME: message

      EVENTUATE_CDC_PIPELINE_PIPELINE2_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_PIPELINE2_READER: reader2
      EVENTUATE_CDC_PIPELINE_PIPELINE2_EVENTUATEDATABASESCHEMA: payment
      #EVENTUATE_CDC_PIPELINE_PIPELINE2_SOURCETABLENAME: message

      EVENTUATE_CDC_READER_READER1_TYPE: mysql-binlog
      EVENTUATE_CDC_READER_READER1_DATASOURCEURL: jdbc:mysql://order-db:3306/eventuate
      EVENTUATE_CDC_READER_READER1_DATASOURCEUSERNAME: user
      EVENTUATE_CDC_READER_READER1_DATASOURCEPASSWORD: password
      EVENTUATE_CDC_READER_READER1_DATASOURCEDRIVERCLASSNAME: com.mysql.jdbc.Driver
      EVENTUATE_CDC_READER_READER1_LEADERSHIPLOCKPATH: /eventuate/cdc/leader/order
      EVENTUATE_CDC_READER_READER1_CDCDBUSERNAME: root
      EVENTUATE_CDC_READER_READER1_CDCDBPASSWORD: root
      EVENTUATE_CDC_READER_READER1_READOLDDEBEZIUMDBOFFSETSTORAGETOPIC: "false"
      EVENTUATE_CDC_READER_READER1_MYSQLBINLOGCLIENTUNIQUEID: 1
      EVENTUATE_CDC_READER_READER1_OFFSETSTOREKEY: MySqlBinlog
      EVENTUATE_CDC_READER_READER1_OFFSETSTORAGETOPICNAME: db.history.order

      EVENTUATE_CDC_READER_READER2_TYPE: mysql-binlog
      EVENTUATE_CDC_READER_READER2_DATASOURCEURL: jdbc:mysql://payment-db:3307/eventuate
      EVENTUATE_CDC_READER_READER2_DATASOURCEUSERNAME: user
      EVENTUATE_CDC_READER_READER2_DATASOURCEPASSWORD: password
      EVENTUATE_CDC_READER_READER2_DATASOURCEDRIVERCLASSNAME: com.mysql.jdbc.Driver
      EVENTUATE_CDC_READER_READER2_LEADERSHIPLOCKPATH: /eventuate/cdc/leader/payment
      EVENTUATE_CDC_READER_READER2_CDCDBUSERNAME: root
      EVENTUATE_CDC_READER_READER2_CDCDBPASSWORD: root
      EVENTUATE_CDC_READER_READER2_READOLDDEBEZIUMDBOFFSETSTORAGETOPIC: "false"
      EVENTUATE_CDC_READER_READER2_MYSQLBINLOGCLIENTUNIQUEID: 2
      EVENTUATE_CDC_READER_READER2_OFFSETSTOREKEY: MySqlBinlog
      EVENTUATE_CDC_READER_READER2_OFFSETSTORAGETOPICNAME: db.history.payment
# <<< cdc

#
# >>> kafka
#
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.4
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:5.2.4
    hostname: kafka
    container_name: kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENERS: LC://kafka:29092,LX://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LC://kafka:29092,LX://${DOCKER_HOST_IP:-localhost}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LC:PLAINTEXT,LX:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LC
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 60000
# <<< kafka

#
# >>> mysql
#
  order-db:
    image: mysql:5.7
    hostname: order-db
    container_name: order-db
    ports:
      - 3306:3306
    volumes:
      - "./docker/order-db/my.cnf:/etc/mysql/conf.d/my.cnf"
      - "./docker/order-db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  payment-db:
    image: mysql:5.7
    hostname: payment-db
    container_name: payment-db
    ports:
      - 3307:3306
    volumes:
      - "./docker/payment-db/my.cnf:/etc/mysql/conf.d/my.cnf"
      - "./docker/payment-db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
# <<< mysql